version: '3.3'
services:
  db:
    container_name: mysql57
    image: mysql:5.7
    restart: always
    command: --disable-partition-engine-check
    environment:
      - MYSQL_DATABASE=bd_buy_food
      - MYSQL_ROOT_PASSWORD=rootmasterkey
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=masterkey
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume:





