server:
  port: 9080
  servlet:
    context-path: /buy-food

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bd_buy_food?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ${mysql-db-username:admin}
    password: ${mysql-db-password:masterkey}
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      file-size-threshold: 2KB
      max-request-size: 5MB

keycloak:
  realm: master
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: buy-food
  credentials:
    secret: ${keycloack-credentials-secret:2abe3b6d-8e5a-4016-a941-84b039117987}
  use-resource-role-mappings: true
  bearer-only: true

keycloak-custom:
  admin-user: ${keycloack-admin-user:admin}
  admin-password: ${keycloack-admin-password:Pa55w0rd}

swagger:
  enabled: true

file:
  upload-dir: ${file-upload-dir:c:/upload/images}