server:
  port: 9080
  servlet:
    context-path: /buy-food

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bd_buy_food?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: admin
    password: masterkey
    initialization-mode: always
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
    generate-ddl: true

keycloak:
  realm: master
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: buy-food
  credentials:
    secret: 2abe3b6d-8e5a-4016-a941-84b039117987
  use-resource-role-mappings: true
  bearer-only: true