# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - buy-food

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Set up secrets action
      env:
        MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
        MYSQL_DB_NAME: ${{ secrets.MYSQL_DB_NAME }}
        MYSQL_DB_USER: ${{ secrets.MYSQL_DB_USER }}
        MYSQL_DB_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
        KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
        KEYCLOAK_SERVER: ${{ secrets.KEYCLOAK_SERVER }}
        KEYCLOAK_CREDENTIALS_SECRET: ${{ secrets.KEYCLOAK_CREDENTIALS_SECRET }}
        KEYCLOACK_ADMIN_USER: ${{ secrets.KEYCLOACK_ADMIN_USER }}
        KEYCLOACK_ADMIN_PASSWORD: ${{ secrets.KEYCLOACK_ADMIN_PASSWORD }}
        FILE_UPLOAD_DIR: ${{ secrets.FILE_UPLOAD_DIR }}
      run: |
        echo "MYSQL_HOST: " $MYSQL_HOST

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'buy-food'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ed76fd8905dd4316b6711eb5098ac26d }}
        package: '${{ github.workspace }}/target/*.jar'